const cardfInfo = [
  {
    id: 1,
    image: "",
    title: "3 Bedroom Detached Duplex",
    semititle: "Lagos State",
    about: "lorm",
    text1: "lorem",
    text2: "powoe",
    text3: "powss",
  },
  {
    id: 2,
    image: "",
    title: "3 Bedroom Detached Duplex",
    semititle: "Ogun State",
    about: "lorm",
    text1: "lorem",
    text2: "powoe",
    text3: "powss",
  },
  {
    id: 3,
    image: "",
    title: "3 Bedroom Detached Duplex",
    semititle: "Oyo State",
    about: "lorm",
    text1: "lorem",
    text2: "powoe",
    text3: "powss",
  },
  {
    id: 4,
    image: "",
    title: "3 Bedroom Detached Duplex",
    semititle: "Lagos State",
    about: "lorm",
    text1: "lorem",
    text2: "powoe",
    text3: "powss",
  },
];
export default cardfInfo;
